### PR TITLE
Annotated the query with the federation partners

### PR DESCRIPTION
**Pull request by JervenBolleman**
Use the ontology created in the ontology branch to annotate that a query federates with certain endpoints.
Tests that the query service clauses match the annotations are also added.

### CODE REVIEW

**Comment by vemonet** [comment]
There is some issue with Bgee proxy which makes services calls to https://www.bgee.org/sparql fail, the ending slash is required for it to work (in SERVICE calls only...), I have added it 
And Ensembl xrefs between uniprot and bgee needs a small rewrite to work (uniprot ensembl IRIs use version number in IRIs, while bgee does not)

**Review by vemonet — APPROVED** [review]

**Comment by vemonet** [comment]
Wouldn't it better to use `spex:federatesWith` instead of `sparql-examples:federates_with` for the predicate? Camecase is usually more commonly used for predicates than snakecase 

For the prefix maybe a shorthand like `spex:` or `rqex:`? Having `-` in the left part of a CURIE is authorized but some coloration systems are not working well with it

**Comment by JervenBolleman** [comment]
@vemonet  spex:federatesWith could you give me a link to the ontology file please

**Comment by vemonet** [comment]
The ontology was pushed in a different PR: https://github.com/sib-swiss/sparql-examples/pull/22

I can make some improvements to the ontology, should I push it back to this PR 22 or this one?

**Comment by JervenBolleman** [comment]
I was thinking you where referring to an ontology associated with zazuko spex.
Yes using camelcase is fine I will fix it.

**Comment by JervenBolleman** [comment]
Redone in https://github.com/sib-swiss/sparql-examples/pull/39

**Pull request closed without merging**
